'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {

    await queryInterface.bulkInsert('alunos',
      [
        { nome: 'Ana', sobrenome: 'Almeida', responsavel: 'Carmem Almeida', endereco: 'Rua 29 de Março', telefone: "(88)25006412", usuario_id: 1 },
        { nome: 'Pedro', sobrenome: 'Almeida', responsavel: 'Carmem Almeida', endereco: 'Rua 29 de Março', telefone: "(88)06919120", usuario_id: 2 },
        { nome: 'Cesar', sobrenome: 'Pinheiro', responsavel: 'Bernardo Pinheiro', endereco: 'Rua Da Flores', telefone: "(88)09412460", usuario_id: 3 },
        { nome: 'Sergio', sobrenome: 'Vieira', responsavel: 'Joelma Vieira', endereco: 'Av. Cônego Nestor', telefone: "(88)43655637", usuario_id: 4 },
        { nome: 'Arnon', sobrenome: 'Coelho', responsavel: 'Paulo Coelho', endereco: 'Av. Castelo Branco', telefone: "(88)43085332", usuario_id: 5 },
        { nome: 'Bernardo', sobrenome: 'Coelho', responsavel: 'Paulo Coelho', endereco: 'Av. Castelo Branco', telefone: "(88)54910484", usuario_id: 6 },
        { nome: 'Sara', sobrenome: 'Carvalho', responsavel: 'Ana Carmem', endereco: 'Rua Duque de Caxias', telefone: "(88)83868101", usuario_id: 7 },
        { nome: 'Ruth', sobrenome: 'Miranda', responsavel: 'Francisco José', endereco: 'Rua Duque de Caxias', telefone: "(88)45993312", usuario_id: 8 },
        { nome: 'Adalton', sobrenome: 'Silva', responsavel: 'Pedro Sousa', endereco: 'Rua Amaral de Lisboa', telefone: "(88)50870929", usuario_id: 9 },
        { nome: 'Gleidson', sobrenome: 'Silva', responsavel: 'Francisco Silva', endereco: 'Rua Duque de Caxias', telefone: "(88)82913230", usuario_id: 10 },
        { nome: 'Bruno', sobrenome: 'Rodrigues', responsavel: 'Sandra Rodrigues', endereco: 'Av. Cônego Nestor', telefone: "(88)42244197", usuario_id: 11 },
        { nome: 'Armando', sobrenome: 'Santos', responsavel: 'Betânia Santos', endereco: 'Rua Duque de Caxias', telefone: "(88)83614801", usuario_id: 12 },
        { nome: 'João', sobrenome: 'Vicente', responsavel: 'Abilene Vicente', endereco: 'Av. Barão do Rio Branco', telefone: "(88)99767717", usuario_id: 13 },
        { nome: 'Débora', sobrenome: 'Amador', responsavel: 'Marcia Amador', endereco: 'Rua São Bernardo', telefone: "(88)13252379", usuario_id: 14 },
        { nome: 'Paulo', sobrenome: 'Amador', responsavel: 'Marcia Amador', endereco: 'Rua São Bernardo', telefone: "(88)64630401", usuario_id: 15 },
        { nome: 'Talita', sobrenome: 'Noqueira', responsavel: 'Luzia Alves', endereco: 'Rua São Vicente', telefone: "(88)09042665", usuario_id: 16 },
        { nome: 'Rodrigo', sobrenome: 'Alves', responsavel: 'Luzia Alves', endereco: 'Rua São Vicente', telefone: "(88)47587099", usuario_id: 17 },
        { nome: 'Daniel', sobrenome: 'Gomes', responsavel: 'Raimundo Alves', endereco: 'Rua São Vicente', telefone: "(88)64017683", usuario_id: 18 },
        { nome: 'Ricardo', sobrenome: 'Alves', responsavel: 'Telma Alves', endereco: 'Rua São Joaquim', telefone: "(88)45311291", usuario_id: 19 },
        { nome: 'Leandro', sobrenome: 'Vieira', responsavel: 'Raimunda Vieira', endereco: 'Rua São Vicente', telefone: "(88)85686354", usuario_id: 20 },
        { nome: 'Dinei', sobrenome: 'Viana', responsavel: 'Alzira Viana', endereco: 'Rua 29 de Março', telefone: "(88)98417637", usuario_id: 21 },
        { nome: 'Maria', sobrenome: 'Alice', responsavel: 'Domingo Batista', endereco: 'Rua Dom Pedro I', telefone: "(88)31296955", usuario_id: 22 },
        { nome: 'Rebeca', sobrenome: 'Linhares', responsavel: 'Bernardo Linhares', endereco: 'Rua Das Palmeiras', telefone: "(88)15091361", usuario_id: 23 },
        { nome: 'Carla', sobrenome: 'Oliveira', responsavel: 'Ana Oliveira', endereco: 'Rua 29 de Março', telefone: "(88)67137797", usuario_id: 24 },
        { nome: 'Felipe', sobrenome: 'Silva', responsavel: 'Antônio Silveira', endereco: 'Travessa Dois Irmãos', telefone: "(88)13804166", usuario_id: 25 },
        { nome: 'Diego', sobrenome: 'Viana', responsavel: 'Claudia Viana', endereco: 'Av. Castelo Branco', telefone: "(88)98311081", usuario_id: 26 },
        { nome: 'Amanda', sobrenome: 'Gomes', responsavel: 'Silvana Gomes', endereco: 'Rua Aquarele', telefone: "(88)49066616", usuario_id: 27 },
        { nome: 'Fabio', sobrenome: 'Zardes', responsavel: 'Antônio Zardes', endereco: 'Rua Heitor Villa Lobos', telefone: "(88)15524603", usuario_id: 28 },
        { nome: 'Maria', sobrenome: 'Silva', responsavel: 'Bernado Silva', endereco: 'Rua Das Palmeiras', telefone: "(88)23929580", usuario_id: 29 },
        { nome: 'Henrique', sobrenome: 'Silveira', responsavel: 'Joana Silveira', endereco: 'Rua São Bernardo', telefone: "(88)00356592", usuario_id: 30 },
        { nome: 'Antônio', sobrenome: 'Silva', responsavel: 'Francisca Silva', endereco: 'Av. Castelo Branco', telefone: "(88)48078273", usuario_id: 31 },
        { nome: 'Paulo', sobrenome: 'Silva', responsavel: 'Maria Francsica', endereco: 'Rua Heitor Villa Lobos', telefone: "(88)21167717", usuario_id: 32 },
        { nome: 'Ana', sobrenome: 'Queiroz', responsavel: 'Joana Queiroz', endereco: 'Av. Castelo Branco', telefone: "(88)68185593", usuario_id: 33 },
        { nome: 'Carla', sobrenome: 'Mendes', responsavel: 'João Mendes', endereco: 'Rua São Vicente', telefone: "(88)44115913", usuario_id: 34 },
        { nome: 'Eliel', sobrenome: 'Silva', responsavel: 'Antônia Silva', endereco: 'Rua Dom Pedro I', telefone: "(88)76358203", usuario_id: 35 },
        { nome: 'Fernando', sobrenome: 'Fernandez', responsavel: 'Glória Maria', endereco: 'Av. Cônego Nestor', telefone: "(88)71313572", usuario_id: 36 },
        { nome: 'Celso', sobrenome: 'Roqdrigues', responsavel: 'Bernada Rodrigues', endereco: 'Av. Dos Ipês', telefone: "(88)66214428", usuario_id: 37 },
        { nome: 'Heitor', sobrenome: 'Salvador', responsavel: 'Jerônimo Salvador', endereco: 'Rua 29 de Março', telefone: "(88)30444916", usuario_id: 38 },
        { nome: 'Amanda', sobrenome: 'Amaro', responsavel: 'Antônia Amaro', endereco: 'Rua das Palmeiras', telefone: "(88)74528705", usuario_id: 39 },
        { nome: 'Claudiane', sobrenome: 'Sousa', responsavel: 'Ester Sousa', endereco: 'Rua 15 de Novembro', telefone: "(88)31871038", usuario_id: 40 },
        { nome: 'João', sobrenome: 'Roqdrigues', responsavel: 'Claudia Rodrigues', endereco: 'Rua 29 de Março', telefone: "(88)84029217", usuario_id: 41 },
        { nome: 'Déborah', sobrenome: 'Portual', responsavel: 'Marcia Portugal', endereco: 'Av. Castelo Branco', telefone: "(88)71713584", usuario_id: 42 },
        { nome: 'Rebeca', sobrenome: 'Santos', responsavel: 'Jonas Santos', endereco: 'Rua Duque de Caxias', telefone: "(88)49779087", usuario_id: 43 },
        { nome: 'Rodrigo', sobrenome: 'Noqueira', responsavel: 'Nerinaldo Noqueira', endereco: 'Rua São Bernado', telefone: "(88)07265727", usuario_id: 44 },
        { nome: 'Luiza', sobrenome: 'Gomes', responsavel: 'Telma Gomes', endereco: 'Rua São Vicente', telefone: "(88)23790608", usuario_id: 45 },
        { nome: 'Karla', sobrenome: 'Alves', responsavel: 'Sara Alves', endereco: 'Rua Duque de Caxias', telefone: "(88)07423996", usuario_id: 46 },
        { nome: 'Ana', sobrenome: 'Sousa', responsavel: 'Claudio Sousa', endereco: 'Rua São Bernardo', telefone: "(88)47017969", usuario_id: 47 },
        { nome: 'Rafael', sobrenome: 'Pietro ', responsavel: 'João Sousa', endereco: 'Rua Das Palmeiras', telefone: "(88)35359356", usuario_id: 48 },
        { nome: 'Flavia', sobrenome: 'Soares ', responsavel: 'Miguel Soares', endereco: 'Rua 15 de Novembro', telefone: "(88)73244413", usuario_id: 49 },
        { nome: 'Sávio', sobrenome: 'Sousa ', responsavel: 'Renan Soares', endereco: 'Av. Castelo Branco', telefone: "(88)11547472", usuario_id: 50 },
        { nome: 'Renata', sobrenome: 'Sousa ', responsavel: 'Celma Gomes', endereco: 'Rua São Vicente', telefone: "(88)63917321", usuario_id: 51 },
        { nome: 'Filipe', sobrenome: 'Bernardes ', responsavel: 'Bento Bernardes', endereco: 'Praça Domingos Rodrigues', telefone: "(88)88463284", usuario_id: 52 },
        { nome: 'Cláudia', sobrenome: 'Assis ', responsavel: 'Raimunda Renata', endereco: 'Rua São Paulo', telefone: "(88)62253086", usuario_id: 53 },
        { nome: 'Amanda', sobrenome: 'Carvalho ', responsavel: 'Carla Carvalho', endereco: 'Rua 29 de Março', telefone: "(88)61859213", usuario_id: 54 },
        { nome: 'Sergio', sobrenome: 'Santos ', responsavel: 'Henrique Santos', endereco: 'Av. Castelo Branco', telefone: "(88)71597906", usuario_id: 55 },
        { nome: 'Ayla', sobrenome: 'Farias ', responsavel: 'Alessandra Natália', endereco: 'Rua 29 de Março', telefone: "(88)55686026", usuario_id: 56 },
        { nome: 'Ian', sobrenome: 'Souza ', responsavel: 'Jaqueline Souza', endereco: 'Rua Dom Pedro I', telefone: "(88)22228866", usuario_id: 57 },
        { nome: 'Nicolas', sobrenome: 'Mota ', responsavel: 'Manuel Mota', endereco: 'Rua 15 de Novembro', telefone: "(88)56616974", usuario_id: 58 },
        { nome: 'Renan', sobrenome: 'Figueiredo ', responsavel: 'Sueli Figueiredo', endereco: 'Rua São Bernardo', telefone: "(88)36712472", usuario_id: 59 },
        { nome: 'Pietro', sobrenome: 'Jesus', responsavel: 'Esther Eliane', endereco: 'Av. Dos Ipês', telefone: "(88)36417325", usuario_id: 60 },
        { nome: 'Helena', sobrenome: 'Moura', responsavel: 'Bento Moura', endereco: 'Rua Xavier Galvão', telefone: "(88)79906923", usuario_id: 61 },
        { nome: 'Eduardo', sobrenome: 'Pereira', responsavel: 'Cláudio Pereira', endereco: 'Rua Alexandre Menezes', telefone: "(88)33098056", usuario_id: 62 },
        { nome: 'Hugo', sobrenome: 'Carvalho', responsavel: 'Benjamin Carvalho', endereco: 'Travessa 1º de Maio', telefone: "(88)95123186", usuario_id: 63 },
        { nome: 'Sophia', sobrenome: 'Portugal', responsavel: 'Ana Portugal', endereco: 'Av. Cônego Nestor', telefone: "(88)92072541", usuario_id: 64 },
        { nome: 'Daniela', sobrenome: 'Rocha', responsavel: 'Lúcia Alice', endereco: 'Rua Rainha Isabel', telefone: "(88)26738146", usuario_id: 65 },
        { nome: 'Yago', sobrenome: 'Martins', responsavel: 'Bernardo Martins', endereco: 'Rua Primareva', telefone: "(88)77440991", usuario_id: 66 },
        { nome: 'Gabriel', sobrenome: 'Pereira', responsavel: 'Betânia Pereira', endereco: 'Rua Jairo de Andrade Lima', telefone: "(88)99837984", usuario_id: 67 },
        { nome: 'Igor', sobrenome: 'Pires', responsavel: 'Osvaldo Pires', endereco: 'Rua Papa Gregório VII', telefone: "(88)56255359", usuario_id: 68 },
        { nome: 'Hadassa', sobrenome: 'Nunes', responsavel: 'Geraldo Nunes', endereco: 'Rua João XX', telefone: "(88)82820291", usuario_id: 69 },
        { nome: 'Adriana', sobrenome: 'Pontes', responsavel: 'Tomás Pontes', endereco: 'Rua Das Rosas', telefone: "(88)15374201", usuario_id: 70 },
        { nome: 'Felipe', sobrenome: 'Neves', responsavel: 'Joana Silva', endereco: 'Travessa 1º de Maio', telefone: "(88)66996099", usuario_id: 71 },
        { nome: 'Theo', sobrenome: 'Moreira', responsavel: 'Elisa Moreira', endereco: 'Rua Xavier Galvão', telefone: "(88)54165604", usuario_id: 72 },
        { nome: 'Pietro', sobrenome: 'Drumond', responsavel: 'Nelson Drumond', endereco: 'Rua Curimatã', telefone: "(88)25986973", usuario_id: 73 },
        { nome: 'Cauã', sobrenome: 'Monteiro', responsavel: 'Flavia Monteiro', endereco: 'Rua Barcelona', telefone: "(88)09675280", usuario_id: 74 },
        { nome: 'Victor', sobrenome: 'Mota', responsavel: 'Cristiane Mota', endereco: 'Rua dos Tupinambás', telefone: "(88)04287106", usuario_id: 75 },
        { nome: 'Mario', sobrenome: 'Andrade', responsavel: 'Antônio Andrade', endereco: 'Av. Cônego Nestor', telefone: "(88)11630676", usuario_id: 76 },
        { nome: 'Pedro', sobrenome: 'Sousa', responsavel: 'Eliane Sousa', endereco: 'Rua Curimatã', telefone: "(88)97094955", usuario_id: 77 },
        { nome: 'Saulo', sobrenome: 'Morais', responsavel: 'Francisco Morais', endereco: 'Rua Curimatã', telefone: "(88)94590350", usuario_id: 78 },
        { nome: 'Lucas', sobrenome: 'Sales', responsavel: 'Célia Sales', endereco: 'Rua dos Tupinambás', telefone: "(88)99170119", usuario_id: 79 },
        { nome: 'Mateus', sobrenome: 'Rodrigues', responsavel: 'Jorge Rodrigues', endereco: 'Rua dos Tupinambás', telefone: "(88)57793706", usuario_id: 80 },
        { nome: 'Jorge', sobrenome: 'Amaro', responsavel: 'Carla Amaro', endereco: 'Rua dos Tupinambás', telefone: "(88)42354321", usuario_id: 81 },
        { nome: 'Sâmia', sobrenome: 'Carvalho', responsavel: 'Pedro Neto', endereco: 'Rua Curimatã', telefone: "(88)41235942", usuario_id: 82 },
        { nome: 'Italo', sobrenome: 'Carvalho', responsavel: 'Sandra Gomes', endereco: 'Rua Rainha Isabel', telefone: "(88)70014329", usuario_id: 83 },
        { nome: 'Igor', sobrenome: 'Santos', responsavel: 'Raimundo Santos', endereco: 'Travessa 1º de Maio', telefone: "(88)41586538", usuario_id: 84 },
        { nome: 'Giovane', sobrenome: 'Viana', responsavel: 'Rosa Viana', endereco: 'Travessa 1º de Maio', telefone: "(88)59481483", usuario_id: 85 },
        { nome: 'João', sobrenome: 'Morales', responsavel: 'Odair Morales', endereco: 'Av. Contagem', telefone: "(88)65104990", usuario_id: 86 },
        { nome: 'Leonardo', sobrenome: 'Araujo', responsavel: 'Ana Araujo', endereco: 'Rua Ouro Branco', telefone: "(88)09857096", usuario_id: 87 },
        { nome: 'Roger', sobrenome: 'Silva', responsavel: 'Isabel Silva', endereco: 'Av. dos Patos', telefone: "(88)22326227", usuario_id: 88 },
        { nome: 'Flávio', sobrenome: 'Almeida', responsavel: 'Tulio Almeida', endereco: 'Rua Irmãos Abreu', telefone: "(88)69368907", usuario_id: 89 },
        { nome: 'Celina', sobrenome: 'Vieira', responsavel: 'Miguel Gomes', endereco: 'Rua Barcelona', telefone: "(88)27059881", usuario_id: 90 },
        { nome: 'José', sobrenome: 'Morais', responsavel: 'Arnaldo Morais', endereco: 'Rua São Bernardo', telefone: "(88)74481856", usuario_id: 91 },
        { nome: 'Alex', sobrenome: 'Monteiro', responsavel: 'Mazé Monteiro', endereco: 'Rua Curimatã', telefone: "(88)51132850", usuario_id: 92 },
        { nome: 'Santiago', sobrenome: 'Alves', responsavel: 'Mario Santiago', endereco: 'Av. Contagem', telefone: "(88)11293159", usuario_id: 93 },
        { nome: 'Vinicius', sobrenome: 'Olivares', responsavel: 'Carlos Delgado', endereco: 'Av. Contagem', telefone: "(88)03431934", usuario_id: 94 },
        { nome: 'Otton', sobrenome: 'Santos', responsavel: 'Helga Santos', endereco: 'Rua Barcelona', telefone: "(88)03752599", usuario_id: 95 },
        { nome: 'Ravena', sobrenome: 'Portugal', responsavel: 'Claudia Portugal', endereco: 'Av. Castelo Branco', telefone: "(88)42052303", usuario_id: 96 },
        { nome: 'Vitoria', sobrenome: 'Portela', responsavel: 'Sara Porto', endereco: 'Av. Castelo Branco', telefone: "(88)58258337", usuario_id: 97 },
        { nome: 'Manoel', sobrenome: 'Silva', responsavel: 'Lindalva Silva', endereco: 'Av. Contagem', telefone: "(88)83196178", usuario_id: 98 },
        { nome: 'Marcos', sobrenome: 'Pontes', responsavel: 'Geovane Carvalho', endereco: 'Rua Ouro Branco', telefone: "(88)35183520", usuario_id: 99 }
      ], {});

  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('alunos', null, {});
  }
};
