'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {

    await queryInterface.bulkInsert('alunos', 
    [
      {nome: 'Ana',sobrenome: 'Almeida',responsavel: 'Carmem Almeida',endereco: 'Rua 29 de Março',telefone: "(88)25006412", usuario_id:100},
      {nome: 'Pedro',sobrenome: 'Almeida',responsavel: 'Carmem Almeida',endereco: 'Rua 29 de Março',telefone: "(88)06919120", usuario_id:101},
      {nome: 'Cesar',sobrenome: 'Pinheiro',responsavel: 'Bernardo Pinheiro',endereco: 'Rua Da Flores',telefone: "(88)09412460", usuario_id:102},
      {nome: 'Sergio',sobrenome: 'Vieira',responsavel: 'Joelma Vieira',endereco: 'Av. Cônego Nestor',telefone: "(88)43655637", usuario_id:103},
      {nome: 'Arnon',sobrenome: 'Coelho',responsavel: 'Paulo Coelho',endereco: 'Av. Castelo Branco',telefone: "(88)43085332", usuario_id:104},
      {nome: 'Bernardo',sobrenome: 'Coelho',responsavel: 'Paulo Coelho',endereco: 'Av. Castelo Branco',telefone: "(88)54910484", usuario_id:105},
      {nome: 'Sara',sobrenome: 'Carvalho',responsavel: 'Ana Carmem',endereco: 'Rua Duque de Caxias',telefone: "(88)83868101", usuario_id:106},
      {nome: 'Ruth',sobrenome: 'Miranda',responsavel: 'Francisco José',endereco: 'Rua Duque de Caxias',telefone: "(88)45993312", usuario_id:107},
      {nome: 'Adalton',sobrenome: 'Silva',responsavel: 'Pedro Sousa',endereco: 'Rua Amaral de Lisboa', telefone: "(88)50870929", usuario_id:108},
      {nome: 'Gleidson',sobrenome: 'Silva',responsavel: 'Francisco Silva',endereco: 'Rua Duque de Caxias', telefone: "(88)82913230", usuario_id:109},
      {nome: 'Bruno',sobrenome: 'Rodrigues',responsavel: 'Sandra Rodrigues',endereco: 'Av. Cônego Nestor', telefone: "(88)42244197", usuario_id:110},
      {nome: 'Armando',sobrenome: 'Santos',responsavel: 'Betânia Santos',endereco: 'Rua Duque de Caxias', telefone: "(88)83614801", usuario_id:111},
      {nome: 'João',sobrenome: 'Vicente',responsavel: 'Abilene Vicente',endereco: 'Av. Barão do Rio Branco', telefone: "(88)99767717", usuario_id:112},
      {nome: 'Débora',sobrenome: 'Amador',responsavel: 'Marcia Amador',endereco: 'Rua São Bernardo', telefone: "(88)13252379", usuario_id:113},
      {nome: 'Paulo',sobrenome: 'Amador',responsavel: 'Marcia Amador',endereco: 'Rua São Bernardo', telefone: "(88)64630401", usuario_id:114},
      {nome: 'Talita',sobrenome: 'Noqueira',responsavel: 'Luzia Alves',endereco: 'Rua São Vicente', telefone: "(88)09042665", usuario_id:115},
      {nome: 'Rodrigo',sobrenome: 'Alves',responsavel: 'Luzia Alves',endereco: 'Rua São Vicente', telefone: "(88)47587099", usuario_id:116},
      {nome: 'Daniel',sobrenome: 'Gomes',responsavel: 'Raimundo Alves',endereco: 'Rua São Vicente', telefone: "(88)64017683", usuario_id:117},
      {nome: 'Ricardo',sobrenome: 'Alves',responsavel: 'Telma Alves',endereco: 'Rua São Joaquim', telefone: "(88)45311291", usuario_id:118},
      {nome: 'Leandro',sobrenome: 'Vieira',responsavel: 'Raimunda Vieira',endereco: 'Rua São Vicente', telefone: "(88)85686354", usuario_id:119},
      {nome: 'Dinei',sobrenome: 'Viana',responsavel: 'Alzira Viana',endereco: 'Rua 29 de Março', telefone: "(88)98417637", usuario_id:120},
      {nome: 'Maria',sobrenome: 'Alice',responsavel: 'Domingo Batista',endereco: 'Rua Dom Pedro I', telefone: "(88)31296955", usuario_id:121},
      {nome: 'Rebeca',sobrenome: 'Linhares',responsavel: 'Bernardo Linhares',endereco: 'Rua Das Palmeiras', telefone: "(88)15091361", usuario_id:122},
      {nome: 'Carla',sobrenome: 'Oliveira',responsavel: 'Ana Oliveira',endereco: 'Rua 29 de Março', telefone: "(88)67137797", usuario_id:123},
      {nome: 'Felipe',sobrenome: 'Silva',responsavel: 'Antônio Silveira',endereco: 'Travessa Dois Irmãos', telefone: "(88)13804166", usuario_id:124},
      {nome: 'Diego',sobrenome: 'Viana',responsavel: 'Claudia Viana',endereco: 'Av. Castelo Branco', telefone: "(88)98311081", usuario_id:125},
      {nome: 'Amanda',sobrenome: 'Gomes',responsavel: 'Silvana Gomes',endereco: 'Rua Aquarele', telefone: "(88)49066616", usuario_id:126},
      {nome: 'Fabio',sobrenome: 'Zardes',responsavel: 'Antônio Zardes',endereco: 'Rua Heitor Villa Lobos', telefone: "(88)15524603", usuario_id:127},
      {nome: 'Maria',sobrenome: 'Silva',responsavel: 'Bernado Silva',endereco: 'Rua Das Palmeiras', telefone: "(88)23929580", usuario_id:128},
      {nome: 'Henrique',sobrenome: 'Silveira',responsavel: 'Joana Silveira',endereco: 'Rua São Bernardo', telefone: "(88)00356592", usuario_id:129},
      {nome: 'Antônio',sobrenome: 'Silva',responsavel: 'Francisca Silva',endereco: 'Av. Castelo Branco', telefone: "(88)48078273", usuario_id:130},
      {nome: 'Paulo',sobrenome: 'Silva',responsavel: 'Maria Francsica',endereco: 'Rua Heitor Villa Lobos', telefone: "(88)21167717", usuario_id:131},
      {nome: 'Ana',sobrenome: 'Queiroz',responsavel: 'Joana Queiroz',endereco: 'Av. Castelo Branco', telefone: "(88)68185593", usuario_id:132},
      {nome: 'Carla',sobrenome: 'Mendes',responsavel: 'João Mendes',endereco: 'Rua São Vicente', telefone: "(88)44115913", usuario_id:133},
      {nome: 'Eliel',sobrenome: 'Silva',responsavel: 'Antônia Silva',endereco: 'Rua Dom Pedro I', telefone: "(88)76358203", usuario_id:134},
      {nome: 'Fernando',sobrenome: 'Fernandez',responsavel: 'Glória Maria',endereco: 'Av. Cônego Nestor', telefone: "(88)71313572", usuario_id:135},
      {nome: 'Celso',sobrenome: 'Roqdrigues',responsavel: 'Bernada Rodrigues',endereco: 'Av. Dos Ipês', telefone: "(88)66214428", usuario_id:136},
      {nome: 'Heitor',sobrenome: 'Salvador',responsavel: 'Jerônimo Salvador',endereco: 'Rua 29 de Março', telefone: "(88)30444916", usuario_id:137},
      {nome: 'Amanda',sobrenome: 'Amaro',responsavel: 'Antônia Amaro',endereco: 'Rua das Palmeiras', telefone: "(88)74528705", usuario_id:138},
      {nome: 'Claudiane',sobrenome: 'Sousa',responsavel: 'Ester Sousa',endereco: 'Rua 15 de Novembro', telefone: "(88)31871038", usuario_id:139},
      {nome: 'João',sobrenome: 'Roqdrigues',responsavel: 'Claudia Rodrigues',endereco: 'Rua 29 de Março', telefone: "(88)84029217", usuario_id:140},
      {nome: 'Déborah',sobrenome: 'Portual',responsavel: 'Marcia Portugal',endereco: 'Av. Castelo Branco', telefone: "(88)71713584", usuario_id:141},
      {nome: 'Rebeca',sobrenome: 'Santos',responsavel: 'Jonas Santos',endereco: 'Rua Duque de Caxias', telefone: "(88)49779087", usuario_id:142},
      {nome: 'Rodrigo',sobrenome: 'Noqueira',responsavel: 'Nerinaldo Noqueira',endereco: 'Rua São Bernado', telefone: "(88)07265727", usuario_id:143},
      {nome: 'Luiza',sobrenome: 'Gomes',responsavel: 'Telma Gomes',endereco: 'Rua São Vicente', telefone: "(88)23790608", usuario_id:144},
      {nome: 'Karla',sobrenome: 'Alves',responsavel: 'Sara Alves',endereco: 'Rua Duque de Caxias', telefone: "(88)07423996", usuario_id:145},
      {nome: 'Ana',sobrenome: 'Sousa',responsavel: 'Claudio Sousa',endereco: 'Rua São Bernardo', telefone: "(88)47017969", usuario_id:146},
      {nome: 'Rafael',sobrenome: 'Pietro ',responsavel: 'João Sousa',endereco: 'Rua Das Palmeiras', telefone: "(88)35359356", usuario_id:147},
      {nome: 'Flavia',sobrenome: 'Soares ',responsavel: 'Miguel Soares',endereco: 'Rua 15 de Novembro', telefone: "(88)73244413", usuario_id:148},
      {nome: 'Sávio',sobrenome: 'Sousa ',responsavel: 'Renan Soares',endereco: 'Av. Castelo Branco', telefone: "(88)11547472", usuario_id:149},
      {nome: 'Renata',sobrenome: 'Sousa ',responsavel: 'Celma Gomes',endereco: 'Rua São Vicente', telefone: "(88)63917321", usuario_id:150},
      {nome: 'Filipe',sobrenome: 'Bernardes ',responsavel: 'Bento Bernardes',endereco: 'Praça Domingos Rodrigues', telefone: "(88)88463284", usuario_id:151},
      {nome: 'Cláudia',sobrenome: 'Assis ',responsavel: 'Raimunda Renata',endereco: 'Rua São Paulo', telefone: "(88)62253086", usuario_id:152},
      {nome: 'Amanda',sobrenome: 'Carvalho ',responsavel: 'Carla Carvalho',endereco: 'Rua 29 de Março', telefone: "(88)61859213", usuario_id:153},
      {nome: 'Sergio',sobrenome: 'Santos ',responsavel: 'Henrique Santos',endereco: 'Av. Castelo Branco', telefone: "(88)71597906", usuario_id:154},
      {nome: 'Ayla',sobrenome: 'Farias ',responsavel: 'Alessandra Natália',endereco: 'Rua 29 de Março', telefone: "(88)55686026", usuario_id:155},
      {nome: 'Ian',sobrenome: 'Souza ',responsavel: 'Jaqueline Souza',endereco: 'Rua Dom Pedro I', telefone: "(88)22228866", usuario_id:156},
      {nome: 'Nicolas',sobrenome: 'Mota ',responsavel: 'Manuel Mota',endereco: 'Rua 15 de Novembro', telefone: "(88)56616974", usuario_id:157},
      {nome: 'Renan',sobrenome: 'Figueiredo ',responsavel: 'Sueli Figueiredo',endereco: 'Rua São Bernardo', telefone: "(88)36712472", usuario_id:158},
      {nome: 'Pietro',sobrenome: 'Jesus',responsavel: 'Esther Eliane',endereco: 'Av. Dos Ipês', telefone: "(88)36417325", usuario_id:159},
      {nome: 'Helena',sobrenome: 'Moura',responsavel: 'Bento Moura',endereco: 'Rua Xavier Galvão', telefone: "(88)79906923", usuario_id:160},
      {nome: 'Eduardo',sobrenome: 'Pereira',responsavel: 'Cláudio Pereira',endereco: 'Rua Alexandre Menezes', telefone: "(88)33098056", usuario_id:161},
      {nome: 'Hugo',sobrenome: 'Carvalho',responsavel: 'Benjamin Carvalho',endereco: 'Travessa 1º de Maio', telefone: "(88)95123186", usuario_id:162},
      {nome: 'Sophia',sobrenome: 'Portugal',responsavel: 'Ana Portugal',endereco: 'Av. Cônego Nestor', telefone: "(88)92072541", usuario_id:163},
      {nome: 'Daniela',sobrenome: 'Rocha',responsavel: 'Lúcia Alice',endereco: 'Rua Rainha Isabel', telefone: "(88)26738146", usuario_id:164},
      {nome: 'Yago',sobrenome: 'Martins',responsavel: 'Bernardo Martins',endereco: 'Rua Primareva', telefone: "(88)77440991", usuario_id:165},
      {nome: 'Gabriel',sobrenome: 'Pereira',responsavel: 'Betânia Pereira',endereco: 'Rua Jairo de Andrade Lima', telefone: "(88)99837984", usuario_id:166},
      {nome: 'Igor',sobrenome: 'Pires',responsavel: 'Osvaldo Pires',endereco: 'Rua Papa Gregório VII', telefone: "(88)56255359", usuario_id:167},
      {nome: 'Hadassa',sobrenome: 'Nunes',responsavel: 'Geraldo Nunes',endereco: 'Rua João XX', telefone: "(88)82820291", usuario_id:168},
      {nome: 'Adriana',sobrenome: 'Pontes',responsavel: 'Tomás Pontes',endereco: 'Rua Das Rosas', telefone: "(88)15374201", usuario_id:169},
      {nome: 'Felipe',sobrenome: 'Neves',responsavel: 'Joana Silva',endereco: 'Travessa 1º de Maio', telefone: "(88)66996099", usuario_id:170},
      {nome: 'Theo',sobrenome: 'Moreira',responsavel: 'Elisa Moreira',endereco: 'Rua Xavier Galvão', telefone: "(88)54165604", usuario_id:171},
      {nome: 'Pietro',sobrenome: 'Drumond',responsavel: 'Nelson Drumond',endereco: 'Rua Curimatã', telefone: "(88)25986973", usuario_id:172},
      {nome: 'Cauã',sobrenome: 'Monteiro',responsavel: 'Flavia Monteiro',endereco: 'Rua Barcelona', telefone: "(88)09675280", usuario_id:173},
      {nome: 'Victor',sobrenome: 'Mota',responsavel: 'Cristiane Mota',endereco: 'Rua dos Tupinambás', telefone: "(88)04287106", usuario_id:174},
      {nome: 'Mario',sobrenome: 'Andrade',responsavel: 'Antônio Andrade',endereco: 'Av. Cônego Nestor', telefone: "(88)11630676", usuario_id:175},
      {nome: 'Pedro',sobrenome: 'Sousa',responsavel: 'Eliane Sousa',endereco: 'Rua Curimatã', telefone: "(88)97094955", usuario_id:176},
      {nome: 'Saulo',sobrenome: 'Morais',responsavel: 'Francisco Morais',endereco: 'Rua Curimatã', telefone: "(88)94590350", usuario_id:177},
      {nome: 'Lucas',sobrenome: 'Sales',responsavel: 'Célia Sales',endereco: 'Rua dos Tupinambás', telefone: "(88)99170119", usuario_id:178},
      {nome: 'Mateus',sobrenome: 'Rodrigues',responsavel: 'Jorge Rodrigues',endereco: 'Rua dos Tupinambás', telefone: "(88)57793706", usuario_id:179},
      {nome: 'Jorge',sobrenome: 'Amaro',responsavel: 'Carla Amaro',endereco: 'Rua dos Tupinambás', telefone: "(88)42354321", usuario_id:180},
      {nome: 'Sâmia',sobrenome: 'Carvalho',responsavel: 'Pedro Neto',endereco: 'Rua Curimatã', telefone: "(88)41235942", usuario_id:181},
      {nome: 'Italo',sobrenome: 'Carvalho',responsavel: 'Sandra Gomes',endereco: 'Rua Rainha Isabel', telefone: "(88)70014329", usuario_id:182},
      {nome: 'Igor',sobrenome: 'Santos',responsavel: 'Raimundo Santos',endereco: 'Travessa 1º de Maio', telefone: "(88)41586538", usuario_id:183},
      {nome: 'Giovane',sobrenome: 'Viana',responsavel: 'Rosa Viana',endereco: 'Travessa 1º de Maio', telefone: "(88)59481483", usuario_id:184},
      {nome: 'João',sobrenome: 'Morales',responsavel: 'Odair Morales',endereco: 'Av. Contagem', telefone: "(88)65104990", usuario_id:185},
      {nome: 'Leonardo',sobrenome: 'Araujo',responsavel: 'Ana Araujo',endereco: 'Rua Ouro Branco', telefone: "(88)09857096", usuario_id:186},
      {nome: 'Roger',sobrenome: 'Silva',responsavel: 'Isabel Silva',endereco: 'Av. dos Patos', telefone: "(88)22326227", usuario_id:187},
      {nome: 'Flávio',sobrenome: 'Almeida',responsavel: 'Tulio Almeida',endereco: 'Rua Irmãos Abreu', telefone: "(88)69368907", usuario_id:188},
      {nome: 'Celina',sobrenome: 'Vieira',responsavel: 'Miguel Gomes',endereco: 'Rua Barcelona', telefone: "(88)27059881", usuario_id:189},
      {nome: 'José',sobrenome: 'Morais',responsavel: 'Arnaldo Morais',endereco: 'Rua São Bernardo', telefone: "(88)74481856", usuario_id:190},
      {nome: 'Alex',sobrenome: 'Monteiro',responsavel: 'Mazé Monteiro',endereco: 'Rua Curimatã', telefone: "(88)51132850", usuario_id:191},
      {nome: 'Santiago',sobrenome: 'Alves',responsavel: 'Mario Santiago',endereco: 'Av. Contagem', telefone: "(88)11293159", usuario_id:192},
      {nome: 'Vinicius',sobrenome: 'Olivares',responsavel: 'Carlos Delgado',endereco: 'Av. Contagem', telefone: "(88)03431934", usuario_id:193},
      {nome: 'Otton',sobrenome: 'Santos',responsavel: 'Helga Santos',endereco: 'Rua Barcelona', telefone: "(88)03752599", usuario_id:194},
      {nome: 'Ravena',sobrenome: 'Portugal',responsavel: 'Claudia Portugal',endereco: 'Av. Castelo Branco', telefone: "(88)42052303", usuario_id:195},
      {nome: 'Vitoria',sobrenome: 'Portela',responsavel: 'Sara Porto',endereco: 'Av. Castelo Branco', telefone: "(88)58258337", usuario_id:196},
      {nome: 'Manoel',sobrenome: 'Silva',responsavel: 'Lindalva Silva',endereco: 'Av. Contagem', telefone: "(88)83196178", usuario_id:197},
      {nome: 'Marcos',sobrenome: 'Pontes',responsavel: 'Geovane Carvalho',endereco: 'Rua Ouro Branco', telefone: "(88)35183520", usuario_id:198}
    ], {});

  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('alunos', null, {});
  }
};
